export const REGIONS = {
  Misthalin: [
    'Vision',
    'Yesteryear',
    'Book of Spells',
    'Unknown Land',
    'Dream',
    'Harmony',
    'Start',
    'Flute Salad',
    'Autumn Voyage',
    'Spooky',
    'Greatness',
    'Expanse',
    'Still Night',
    'Venture',
    'Barbarianism',
    'Spirit',
    'Soul Wars',
    'Garden',
    'Medieval',
    'Forever',
    'The Trade Parade',
    'The Waiting Game',
    'Adventure',
    'Lullaby',
    'Doorways',
    'Parade',
  ],
  Karamja: [
    'Jungle Island',
    'Sea Shanty',
    'Jolly R',
    'Landlubber',
    'High Seas',
    'Jungly 2',
    'Jungly 3',
    'Tribal Background',
    'Reggae',
    'Reggae 2',
    'Spooky Jungle',
    'Ambient Jungle',
    'Jungle Troubles',
    'The Shadow',
    'Tribal',
    'Tribal 2',
    'Fanfare 2',
    'Jungly 1',
  ],
  Asgarnia: [
    'Alone',
    'Arrival',
    'Attention',
    'Background',
    'Dwarf Theme',
    'Emperor',
    'Fanfare',
    'Goblin Village',
    'Horizon',
    'Ice Melody',
    'Kingdom',
    'Knightmare',
    'Lightness',
    'Long Way Home',
    'The Maze',
    'Miles Away',
    'Mudskipper Melody',
    'Nightfall',
    'Principality',
    'Scape Soft',
    'Sea Shanty 2',
    'Splendour',
    'Tomorrow',
    'Wander',
    'Workshop',
  ],
  Fremennik: [
    'Saga',
    'Legend',
    'Rellekka',
    'Borderland',
    'Settlement',
    'Poles Apart',
    'The Desolate Isle',
    'Norse Code',
    'Volcanic Vikings',
    'Island of the Trolls',
    'The Galleon',
    'The Lunar Isle',
    'Isle of Everywhere',
    'The Desolate Isle',
    'Exposed',
    'Have an Ice Day',
    'Miscellania',
    'Etceteria',
  ],
  Kandarin: [
    'Anywhere',
    'Island Life',
    'Attack 1',
    'Attack 4',
    'Ballad of Enchantment',
    'Baroque',
    'Big Chords',
    'Camelot',
    'Castle Wars',
    'Chompy Hunt',
    'Creature Cruelty',
    "Eagles' Peak",
    'Emotion',
    'Expecting',
    'Fanfare 3',
    'Fishing',
    'Fruits de Mer',
    'Gaol',
    'Gnome King',
    'Gnome Village',
    'Gnome Village 2',
    'Gnomeball',
    'Grumpy',
    'In the Manor',
    'Joy of the Hunt',
    'Knightly',
    'Lasting',
    'Legend',
    'Legion',
    'Lighthouse',
    'Lightwalk',
    'Long Ago',
    'Lullaby',
    'Magic Dance',
    'Magic Magic Magic',
    'Magical Journey',
    'March',
    'Marooned',
    'Mellow',
    'Melodrama',
    'The Mollusc Menace',
    'Monarch Waltz',
    'Monkey Madness',
    'Mythical',
    'Neverland',
    'On the Wing',
    'Overpass',
    'Overture',
    'Romper Chomper',
    'Sad Meadow',
    'Saga',
    'Serenade',
    'Soundscape',
    'Talking Forest',
    'Theme',
    'The Tower',
    'Tree Spirits',
    'Trinity',
    'Upcoming',
    'Voyage',
    'Waterfall',
    'Wonderous',
    'Work Work Work',
    'Zogre Dance',
  ],
  Desert: [
    'Arabian',
    'Arabian 2',
    'Arabian 3',
    'Desert Heat',
    'Desert Voyage',
    'Egypt',
    'Scarab',
    'Sphinx',
    'Sunburn',
    'The Desert',
    'Over to Nardah',
    'Ruins of Isolation',
    'The Golem',
    "Pharaoh's Tomb",
    'Nomad',
    'Bandit Camp',
    'Al Kharid',
    "The Emir's Arena",
    'Shine',
    'City of the Dead',
    'Dunes of Eternity',
    'Tempor of the Storm',
  ],
  Morytania: [
    'Arabian',
    'Arboretum',
    'Bloodbath',
    'Bone Dance',
    'Catacombs and Tombs',
    'Dance of the Undead',
    'Dead Quiet',
    'Deadlands',
    'Distant Land',
    'Dragontooth Island',
    "Fenkenstrain's Refrain",
    'Lament for the Hallowed',
    'The Last Shanty',
    'Morytania',
    'Natural',
    'Night of the Vampyre',
    'The Other Side',
    'Shadowland',
    'Shipwrecked',
    'Stagnant',
    'Temple of Tribes',
    'The Terrible Tower',
    'Upir Likhyi',
    'Village',
    'Waterlogged',
    'Welcome to the Theatre',
    'Darkmeyer',
    'Trouble Brewing',
    'Zombiism',
  ],
  Tirannwn: [
    'Everywhere',
    'Elven Seed',
    'Crystal Castle',
    'Woodland',
    'Breeze',
    'Elven Mist',
    'Meridian',
    'Forest',
    'Far Away',
    'Riverside',
    'Exposed',
    'Lost Soul',
    'Thrall of the Serpent',
    'Coil',
  ],
  Wilderness: [
    'Army of Darkness',
    'Close Quarters',
    'Crystal Sword',
    'Dangerous',
    'Dark',
    'Dead Can Dance',
    'Deep Wildy',
    'Dragontooth Island',
    'The Enclave',
    'Everlasting Fire',
    'Faithless',
    "Fenkenstrain's Refrain",
    'Forbidden',
    'Inspiration',
    'Mage Arena',
    'Moody',
    'The Other Side',
    'Pirates of Peril',
    'Preservation',
    'Preserved',
    'Regal',
    'Scape Sad',
    'Scape Wild',
    'Shining',
    'Shipwrecked',
    'The Terrible Tower',
    'Troubled',
    'Undercurrent',
    'Underground',
    'Venomous',
    'Wild Isle',
    'Wild Side',
    'Wilderness',
    'Wilderness 2',
    'Wilderness 3',
    'Wildwood',
    'Witching',
    'Wonder',
  ],
  Kourend: [
    'Arcane (music track)',
    'Beyond the Meadow',
    'Burning Desire',
    'Country Jig',
    'The Desolate Mage',
    'The Doors of Dinh',
    'Down by the Docks',
    "A Farmer's Grind",
    'The Forests of Shayzien',
    'The Forlorn Homestead',
    'The Forsaken Tower',
    'Gill Bill',
    'Grow Grow Grow',
    'Hoe Down',
    'Ice and Fire',
    'Kourend the Magnificent',
    'March of the Shayzien',
    'Military Life',
    'The Militia',
    'Newbie Farming',
    'Not a Moment of Relief',
    'Out at the Mines',
    'Rose',
    'Rugged Terrain',
    'Servants of Strife',
    'Soul Fall',
    'Strangled',
    'Stuck in the Mire',
    'A Walk in the Woods',
    'Ascent',
    'Dwarven Domain',
    'Getting Down to Business',
    'On the Frontline',
  ],
  Varlamore: [
    'Are You Not Entertained',
    'The City of Sun',
    'Emissaries of Twilight',
    'The Feathered Serpent',
    'The Guidance of Ralos',
    'Mistrock',
    'Ready for the Hunt',
    'Stones of Old',
    "Varlamore's Sunset",
    'Whispering Wind',
    'Peace and Prosperity',
    'Isle of Serenity',
    'The Undying Light',
    'Creatures of Varlamore',
    'Strangled',
  ],
};

export type Region = keyof typeof REGIONS;
