import { filterDungeons } from '../scripts/filter-regions';

export const UNDERGROUND_TRACKS_STRICT = filterDungeons({ strict: true }); // tracks that exist ONLY underground
export const UNDERGROUND_TRACKS = filterDungeons({ strict: false });

export const REGIONS = {
  Misthalin: [
    'Vision',
    'Yesteryear',
    'Book of Spells',
    'Unknown Land',
    'Dream',
    'Harmony',
    'Start',
    'Flute Salad',
    'Autumn Voyage',
    'Spooky',
    'Greatness',
    'Expanse',
    'Still Night',
    'Venture',
    'Barbarianism',
    'Spirit',
    'Soul Wars',
    'Garden',
    'Medieval',
    'Forever',
    'The Trade Parade',
    'The Waiting Game',
    'Adventure',
    'Lullaby',
    'Doorways',
    'Parade',
    'Newbie Melody',
    'Looking Back',
    'Preserved',
    'Preservation',
    'Cave of the Goblins',
    'Down Below',
    'Harmony 2',
    'The Lost Melody',
    'Monster Melee',
    'Oh Rats!',
    'The Power of Tears',
    'Safety in Numbers',
    'Scape Cave',
    'Tears of Guthix',
    'Tiptoe',
    'Victory is Mine',
    'Title Fight',
    'Crystal Cave',
    'Dance of Death',
    'Dogs of War',
    'Dorgeshuun City',
    'Faerie',
    'Food for Thought',
    'Fossilised',
    'Lava is Mine',
    'Malady',
    'Colossus of the Deep',
    'Scar Tissue',
    'Temple of the Eye',
    'Guardians of the Rift',
    'The Guardians Prepare',
    'The Sound of Guthix',
    'Temple Desecrated',
    'Zealot',
    'Down to Earth',
    'Miracle Dance',
    'Heart and Mind',
    'Stratosphere',
    'Chickened Out',
    'Clanliness',
    'Roots and Flutes',
    'Alternative Root',
    "All's Fairy in Love & War",
  ],
  Karamja: [
    'Jungle Island',
    'Sea Shanty',
    'Jolly R',
    'Landlubber',
    'High Seas',
    'Jungly 2',
    'Jungly 3',
    'Tribal Background',
    'Reggae',
    'Reggae 2',
    'Spooky Jungle',
    'Ambient Jungle',
    'Jungle Troubles',
    'The Shadow',
    'Tribal',
    'Tribal 2',
    'Fanfare 2',
    'Jungly 1',
    '7th Realm',
    'Attack 2',
    'Aztec',
    'Dangerous Road',
    'Karamja Jam',
    'Nether Realm',
    'Pathways',
    'Fire and Brimstone',
    'In the Pits',
    'Mor Ul Rek',
    'TzHaar!',
    'Inferno',
    'Understanding',
    'Superstition',
    'Voodoo Cult',
    'Marooned',

  ],
  Asgarnia: [
    'Alone',
    'Arrival',
    'Attention',
    'Background',
    'Dwarf Theme',
    'Emperor',
    'Fanfare',
    'Goblin Village',
    'Horizon',
    'Ice Melody',
    'Kingdom',
    'Knightmare',
    'Lightness',
    'Long Way Home',
    'The Maze',
    'Miles Away',
    'Mudskipper Melody',
    'Nightfall',
    'Principality',
    'Scape Soft',
    'Sea Shanty 2',
    'Song of the Silent Choir',
    'Splendour',
    'Tomorrow',
    'Wander',
    'Workshop',
    'Frostbite',
    'Stranded',
    'Contest',
    'Tremble',
    'Sojourn',
    'Hells Bells',
    'Romancing the Crone',
    'Pest Control',
    'Null and Void',
    "Warriors' Guild",
    'The Ancient Prison',
    "The Angel's Fury",
    'Arabique',
    'Armageddon',
    'Armadyl Alliance',
    'Bandos Battalion',
    'Strength of Saradomin',
    'Zamorak Zoo',
    'Beyond',
    'Cave Background',
    'Courage',
    'Dunjun',
    'The Mad Mole',
    'Pick & Shovel',
    'Royale',
    'The Ruins of Camdozaal',
    'Starlight',
    'Zaros Zeitgeist',
    'Righteousness',
    'Woe of the Wyvern',
    'Black of Knight',
    'The Route of All Evil',
    'The Fallen Empire',
    'Serene',

  ],
  Fremennik: [
    'Saga',
    'Legend',
    'Rellekka',
    'Borderland',
    'Settlement',
    'Poles Apart',
    'The Desolate Isle',
    'Norse Code',
    'Volcanic Vikings',
    'Island of the Trolls',
    'The Galleon',
    'The Lunar Isle',
    'Isle of Everywhere',
    'The Desolate Isle',
    'Exposed',
    'Eye See You',
    'Have an Ice Day',
    'Miscellania',
    'Etceteria',
    'Barren Land',
    'Lumbering',
    'On Thin Ice',
    'Lighthouse',
    'Corridors of Power',
    'Espionage',
    'Lair of the Basilisk',
    'Land Down Under',
    'Land of the Dwarves',
    'Marzipan',
    'Masquerade',
    'More Than Meets the Eye',
    'The Monsters Below',
    'Ogre the Top',
    'Prison Break',
    'Secrets of the North',
    'The Slayer',
    'Slither and Thither',
    'Tale of Keldagrim',
    'Time to Mine',
    'Prison Break',
    'More Than Meets the Eye',
    'The North',
    'Reign of the Basilisk',
    'The Forsaken',
    'Out of the Deep',
  ],
  Kandarin: [
    'Anywhere',
    'Island Life',
    'Attack 1',
    'Attack 4',
    'Ballad of Enchantment',
    'Baroque',
    'Big Chords',
    'Camelot',
    'Castle Wars',
    'Chompy Hunt',
    'Creature Cruelty',
    "Eagles' Peak",
    'Emotion',
    'Expecting',
    'Fanfare 3',
    'Fishing',
    'Fruits de Mer',
    'Gaol',
    'Gnome King',
    'Gnome Village',
    'Gnome Village 2',
    'Gnomeball',
    'Grumpy',
    'In the Manor',
    'Joy of the Hunt',
    'Knightly',
    'Lasting',
    'Legion',
    'Lightwalk',
    'Long Ago',
    'Lullaby',
    'Magic Dance',
    'Magic Magic Magic',
    'Magical Journey',
    'March',
    'Mellow',
    'Melodrama',
    'The Mollusc Menace',
    'Monarch Waltz',
    'Monkey Madness',
    'Mythical',
    'Neverland',
    'On the Wing',
    'Overpass',
    'Overture',
    'Romper Chomper',
    'Sad Meadow',
    'Serenade',
    'Soundscape',
    'Talking Forest',
    'Theme',
    'The Tower',
    'Tree Spirits',
    'Trinity',
    'Upcoming',
    'Voyage',
    'Waterfall',
    'Wonderous',
    'Work Work Work',
    'Zogre Dance',
    'Making Waves',
    'Jungle Hunt',
    'On the Shore',
    'Altar Ego',
    'Barb Wire',
    'Beneath the Stronghold',
    "Brimstail's Scales",
    'The Cellar Dwellers',
    'Escape',
    'Goblin Game',
    'Devils May Care',
    "Narnode's Theme",
    'Troubled Waters',

    'Cursed',
    'Temple of Tribes',
    'Catacombs and Tombs',
    'Monkey Badness',
    'Monkey Business',
    'Fight or Flight',
    'Temple of Light',
    'La Mort',
    'Iban',
    'Underground Pass',
    'Intrepid',
  ],
  Desert: [
    'Arabian',
    'Arabian 2',
    'Arabian 3',
    'Desert Heat',
    'Desert Voyage',
    'Egypt',
    'Scarab',
    'Sphinx',
    'Sunburn',
    'The Desert',
    'Over to Nardah',
    'Ruins of Isolation',
    'The Golem',
    "Pharaoh's Tomb",
    'Nomad',
    'Bandit Camp',
    'Al Kharid',
    "The Emir's Arena",
    'Shine',
    'City of the Dead',
    'Dunes of Eternity',
    'Tempor of the Storm',
    'Dynasty',
    'Back to Life',
    'The Foundry',
    'Insect Queen',
    'Into the Tombs',

    'Bone Dry',
    'Garden of Winter',
    'Garden of Summer',
    'Garden of Autumn',
    'Garden of Spring',
    'Quest',
    'Beneath Cursed Sands',
    "A Mother's Curse",
    "Jaws of Gluttony", 
    "Sands of Time",
    "Ape-ex Predator",
    "Amascut's Promise",
    "Laid to Rest",
    'Test of Strength', 
    'Test of Isolation',
    'Test of Companionship',
    'Test of Resourcefulness'

  ],
  Morytania: [
    'Arboretum',
    'Bloodbath',
    'Bone Dance',
    'Dance of the Undead',
    'Dead Quiet',
    'Deadlands',
    'Distant Land',
    'Dragontooth Island',
    "Fenkenstrain's Refrain",
    'Lament for the Hallowed',
    'The Last Shanty',
    'Morytania',
    'Natural',
    'Night of the Vampyre',
    'The Other Side',
    'Shadowland',
    'Shipwrecked',
    'Stagnant',
    'Upir Likhyi',
    'Village',
    'Waterlogged',
    'Welcome to the Theatre',
    'Darkmeyer',
    'Trouble Brewing',
    'Zombiism',
    "Life's a Beach!",
    'In the Brine',
    'Distillery Hilarity',
    'Noxious Awakening',
    'Barking Mad',
    'Brew Hoo Hoo!',
    'Body Parts',
    'The Terrible Tunnels',
    'The Terrible Caverns',
    'The Everlasting Slumber',
    'Itsy Bitsy...',
    'Lair',
    'Mausoleum',
    'Phasmatys',
    'Spooky 2',
    'The Terrible Tower',
    'Aye Car Rum Ba',
    'Blistering Barnacles',
    'Little Cave of Horrors',
    'Lament of Meiyerditch',

    "The Maiden's Sorrow",
    "The Maiden's Anger",
    "Welcome to my Nightmare",
    "The Nightmare Continues",
    "Dance of the Nylocas",
    "Arachnids of Vampyrium",
    "The Dark Beast Sotetseg",
    "Power of the Shadow Realm",
    'Predator Xarpus',
    "Last King of the Yarasa",
    "It's not over 'til...",
    "The Fat Lady Sings",
    "The Curtain Closes",
    "Haunted Mine",
    "Deep Down",
    "Chamber"


  ],
  Tirannwn: [
    'Everywhere',
    'Elven Seed',
    'Crystal Castle',
    'Woodland',
    'Breeze',
    'Elven Mist',
    'Meridian',
    'Forest',
    'Far Away',
    'Riverside',
    'Exposed',
    'Lost Soul',
    'Thrall of the Serpent',
    'Coil',
    'Sharp End of the Crystal',
    'Song of the Elves',
    'The Spurned Demon',
    'Trahaearn Toil',
  ],
  Wilderness: [
    'A Dangerous Game',
    'Army of Darkness',
    'Close Quarters',
    'Crystal Sword',
    'Dangerous',
    'Dark',
    'Dead Can Dance',
    'Deep Wildy',
    'Everlasting Fire',
    'Faithless',
    'Forbidden',
    'Inspiration',
    'Mage Arena',
    'Moody',
    'Pirates of Peril',
    'Regal',
    'Scape Sad',
    'Scape Wild',
    'Shining',
    'Troubled',
    'Undercurrent',
    'Underground',
    'Venomous',
    'Wild Isle',
    'Wild Side',
    'Wilderness',
    'Wilderness 2',
    'Wilderness 3',
    'Wildwood',
    'Witching',
    'Wonder',
    'The Enclave',
    'Bane',
    'Cavern',
    'A Dangerous Game',
    'Revenants',
    'Scorpia Dances',
    'Shining Spirit',
    'Attack 3',
    'Attack 5',
    'Last Man Standing',

    'Complication',
  ],
  Kourend: [
    'Arcane',
    'Beyond the Meadow',
    'Burning Desire',
    'Blood Rush',
    'Country Jig',
    'The Desolate Mage',
    'The Doors of Dinh',
    'Down by the Docks',
    "A Farmer's Grind",
    'The Forests of Shayzien',
    'The Forlorn Homestead',
    'The Forsaken Tower',
    'Gill Bill',
    'Grow Grow Grow',
    'Hoe Down',
    'Ice and Fire',
    'Kourend the Magnificent',
    'March of the Shayzien',
    'Military Life',
    'The Militia',
    'Newbie Farming',
    'Not a Moment of Relief',
    'Out at the Mines',
    'Rose',
    'Rugged Terrain',
    'Servants of Strife',
    'Soul Fall',
    'Strangled',
    'Stuck in the Mire',
    'A Walk in the Woods',
    'Ascent',
    'Dwarven Domain',
    'Getting Down to Business',
    'On the Frontline',
    'Beneath the Kingdom',
    'A Forgotten Religion',
    'Sarachnis',
    'Scape Cave',
    'Subterranea',
    'Alchemical Attack!',
    'Creeping Vines',
    'Ful to the Brim',
    'Kanon of Kahlith',

    'Darkly Altared',
    'A Thorn in My Side',
    'Way of the Wyrm',
    'Dagannoth Dawn',
    'Xenophobe',
  ],
  Varlamore: [
    'Are You Not Entertained',
    'The City of Sun',
    'Emissaries of Twilight',
    'The Feathered Serpent',
    'The Guidance of Ralos',
    'Mistrock',
    'Ready for the Hunt',
    'Stones of Old',
    "Varlamore's Sunset",
    'Whispering Wind',
    'Peace and Prosperity',
    'Isle of Serenity',
    'The Undying Light',
    'Creatures of Varlamore',
    'Strangled',
    'Prospering Fortune',
    'Lost to Time',
    'The Moons of Ruin',
    'Under the Mountain',
    'Blood Rush',

    'The Guardian of Tapoyauik',
  ],
};
export const TOTAL_TRACK_COUNT = Object.keys(REGIONS).reduce(
  (count, region) => count + REGIONS[region as Region].length,
  0,
);
export type Region = keyof typeof REGIONS;
